# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 560)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 150, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.cSlider = QtWidgets.QSlider(self.centralWidget)
        self.cSlider.setGeometry(QtCore.QRect(540, 310, 261, 22))
        self.cSlider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cSlider.setMaximum(180)
        self.cSlider.setSingleStep(22)
        self.cSlider.setPageStep(22)
        self.cSlider.setProperty("value", 0)
        self.cSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cSlider.setInvertedAppearance(False)
        self.cSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.cSlider.setObjectName("cSlider")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(290, 250, 131, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txtTemp = QtWidgets.QLineEdit(self.centralWidget)
        self.txtTemp.setGeometry(QtCore.QRect(290, 210, 131, 31))
        self.txtTemp.setObjectName("txtTemp")
        self.txtFlow = QtWidgets.QLineEdit(self.centralWidget)
        self.txtFlow.setGeometry(QtCore.QRect(470, 210, 131, 31))
        self.txtFlow.setObjectName("txtFlow")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(470, 250, 131, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(610, 340, 131, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.hSlider = QtWidgets.QSlider(self.centralWidget)
        self.hSlider.setGeometry(QtCore.QRect(100, 310, 261, 22))
        self.hSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hSlider.setMaximum(180)
        self.hSlider.setSingleStep(22)
        self.hSlider.setPageStep(22)
        self.hSlider.setProperty("value", 0)
        self.hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider.setInvertedAppearance(False)
        self.hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider.setObjectName("hSlider")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(160, 350, 131, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.manualButton = QtWidgets.QRadioButton(self.centralWidget)
        self.manualButton.setGeometry(QtCore.QRect(40, 90, 261, 41))
        self.manualButton.setObjectName("manualButton")
        self.pshBut2 = QtWidgets.QPushButton(self.centralWidget)
        self.pshBut2.setGeometry(QtCore.QRect(490, 150, 91, 29))
        self.pshBut2.setObjectName("pshBut2")
        self.c0 = QtWidgets.QPushButton(self.centralWidget)
        self.c0.setGeometry(QtCore.QRect(780, 410, 21, 21))
        self.c0.setObjectName("c0")
        self.c1 = QtWidgets.QPushButton(self.centralWidget)
        self.c1.setGeometry(QtCore.QRect(750, 410, 21, 21))
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QPushButton(self.centralWidget)
        self.c2.setGeometry(QtCore.QRect(720, 410, 21, 21))
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QPushButton(self.centralWidget)
        self.c3.setGeometry(QtCore.QRect(690, 410, 21, 21))
        self.c3.setObjectName("c3")
        self.c7 = QtWidgets.QPushButton(self.centralWidget)
        self.c7.setGeometry(QtCore.QRect(570, 410, 21, 21))
        self.c7.setObjectName("c7")
        self.c6 = QtWidgets.QPushButton(self.centralWidget)
        self.c6.setGeometry(QtCore.QRect(600, 410, 21, 21))
        self.c6.setObjectName("c6")
        self.c4 = QtWidgets.QPushButton(self.centralWidget)
        self.c4.setGeometry(QtCore.QRect(660, 410, 21, 21))
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QPushButton(self.centralWidget)
        self.c5.setGeometry(QtCore.QRect(630, 410, 21, 21))
        self.c5.setObjectName("c5")
        self.c8 = QtWidgets.QPushButton(self.centralWidget)
        self.c8.setGeometry(QtCore.QRect(540, 410, 21, 21))
        self.c8.setObjectName("c8")
        self.h0 = QtWidgets.QPushButton(self.centralWidget)
        self.h0.setGeometry(QtCore.QRect(100, 410, 21, 21))
        self.h0.setObjectName("h0")
        self.h5 = QtWidgets.QPushButton(self.centralWidget)
        self.h5.setGeometry(QtCore.QRect(250, 410, 21, 21))
        self.h5.setObjectName("h5")
        self.h6 = QtWidgets.QPushButton(self.centralWidget)
        self.h6.setGeometry(QtCore.QRect(280, 410, 21, 21))
        self.h6.setObjectName("h6")
        self.h2 = QtWidgets.QPushButton(self.centralWidget)
        self.h2.setGeometry(QtCore.QRect(160, 410, 21, 21))
        self.h2.setObjectName("h2")
        self.h4 = QtWidgets.QPushButton(self.centralWidget)
        self.h4.setGeometry(QtCore.QRect(220, 410, 21, 21))
        self.h4.setObjectName("h4")
        self.h3 = QtWidgets.QPushButton(self.centralWidget)
        self.h3.setGeometry(QtCore.QRect(190, 410, 21, 21))
        self.h3.setObjectName("h3")
        self.h8 = QtWidgets.QPushButton(self.centralWidget)
        self.h8.setGeometry(QtCore.QRect(340, 410, 21, 21))
        self.h8.setObjectName("h8")
        self.h1 = QtWidgets.QPushButton(self.centralWidget)
        self.h1.setGeometry(QtCore.QRect(130, 410, 21, 21))
        self.h1.setObjectName("h1")
        self.h7 = QtWidgets.QPushButton(self.centralWidget)
        self.h7.setGeometry(QtCore.QRect(310, 410, 21, 21))
        self.h7.setObjectName("h7")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 890, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "please work"))
        self.label.setText(_translate("MainWindow", "Temperature (C)"))
        self.label_2.setText(_translate("MainWindow", "Flow Rate"))
        self.label_3.setText(_translate("MainWindow", "Cold"))
        self.label_4.setText(_translate("MainWindow", "Hot"))
        self.manualButton.setText(_translate("MainWindow", "Faucet Handle Control"))
        self.pshBut2.setText(_translate("MainWindow", "Stop"))
        self.c0.setText(_translate("MainWindow", "0"))
        self.c1.setText(_translate("MainWindow", "1"))
        self.c2.setText(_translate("MainWindow", "2"))
        self.c3.setText(_translate("MainWindow", "3"))
        self.c7.setText(_translate("MainWindow", "7"))
        self.c6.setText(_translate("MainWindow", "6"))
        self.c4.setText(_translate("MainWindow", "4"))
        self.c5.setText(_translate("MainWindow", "5"))
        self.c8.setText(_translate("MainWindow", "8"))
        self.h0.setText(_translate("MainWindow", "0"))
        self.h5.setText(_translate("MainWindow", "5"))
        self.h6.setText(_translate("MainWindow", "6"))
        self.h2.setText(_translate("MainWindow", "2"))
        self.h4.setText(_translate("MainWindow", "4"))
        self.h3.setText(_translate("MainWindow", "3"))
        self.h8.setText(_translate("MainWindow", "8"))
        self.h1.setText(_translate("MainWindow", "1"))
        self.h7.setText(_translate("MainWindow", "7"))

