# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow64buttons.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 560)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.cSlider = QtWidgets.QSlider(self.centralWidget)
        self.cSlider.setGeometry(QtCore.QRect(580, 60, 261, 22))
        self.cSlider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cSlider.setMaximum(180)
        self.cSlider.setSingleStep(22)
        self.cSlider.setPageStep(22)
        self.cSlider.setProperty("value", 0)
        self.cSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cSlider.setInvertedAppearance(False)
        self.cSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.cSlider.setObjectName("cSlider")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 131, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txtTemp = QtWidgets.QLineEdit(self.centralWidget)
        self.txtTemp.setGeometry(QtCore.QRect(20, 50, 131, 31))
        self.txtTemp.setObjectName("txtTemp")
        self.txtFlow = QtWidgets.QLineEdit(self.centralWidget)
        self.txtFlow.setGeometry(QtCore.QRect(170, 50, 131, 31))
        self.txtFlow.setObjectName("txtFlow")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(170, 90, 131, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(650, 90, 131, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.hSlider = QtWidgets.QSlider(self.centralWidget)
        self.hSlider.setGeometry(QtCore.QRect(310, 60, 261, 22))
        self.hSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hSlider.setMaximum(180)
        self.hSlider.setSingleStep(22)
        self.hSlider.setPageStep(22)
        self.hSlider.setProperty("value", 0)
        self.hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider.setInvertedAppearance(False)
        self.hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider.setObjectName("hSlider")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(380, 90, 131, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.manualButton = QtWidgets.QRadioButton(self.centralWidget)
        self.manualButton.setGeometry(QtCore.QRect(20, 10, 261, 41))
        self.manualButton.setObjectName("manualButton")
        self.pshBut2 = QtWidgets.QPushButton(self.centralWidget)
        self.pshBut2.setGeometry(QtCore.QRect(530, 10, 91, 29))
        self.pshBut2.setObjectName("pshBut2")
        self.c0 = QtWidgets.QPushButton(self.centralWidget)
        self.c0.setGeometry(QtCore.QRect(780, 410, 21, 21))
        self.c0.setObjectName("c0")
        self.c1 = QtWidgets.QPushButton(self.centralWidget)
        self.c1.setGeometry(QtCore.QRect(220, 450, 41, 41))
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QPushButton(self.centralWidget)
        self.c2.setGeometry(QtCore.QRect(260, 450, 41, 41))
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QPushButton(self.centralWidget)
        self.c3.setGeometry(QtCore.QRect(300, 450, 41, 41))
        self.c3.setObjectName("c3")
        self.c7 = QtWidgets.QPushButton(self.centralWidget)
        self.c7.setGeometry(QtCore.QRect(460, 450, 41, 41))
        self.c7.setObjectName("c7")
        self.c6 = QtWidgets.QPushButton(self.centralWidget)
        self.c6.setGeometry(QtCore.QRect(420, 450, 41, 41))
        self.c6.setObjectName("c6")
        self.c4 = QtWidgets.QPushButton(self.centralWidget)
        self.c4.setGeometry(QtCore.QRect(340, 450, 41, 41))
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QPushButton(self.centralWidget)
        self.c5.setGeometry(QtCore.QRect(380, 450, 41, 41))
        self.c5.setObjectName("c5")
        self.c8 = QtWidgets.QPushButton(self.centralWidget)
        self.c8.setGeometry(QtCore.QRect(500, 450, 41, 41))
        self.c8.setObjectName("c8")
        self.h0 = QtWidgets.QPushButton(self.centralWidget)
        self.h0.setGeometry(QtCore.QRect(180, 450, 41, 41))
        self.h0.setObjectName("h0")
        self.h5 = QtWidgets.QPushButton(self.centralWidget)
        self.h5.setGeometry(QtCore.QRect(180, 250, 41, 41))
        self.h5.setObjectName("h5")
        self.h6 = QtWidgets.QPushButton(self.centralWidget)
        self.h6.setGeometry(QtCore.QRect(180, 210, 41, 41))
        self.h6.setObjectName("h6")
        self.h2 = QtWidgets.QPushButton(self.centralWidget)
        self.h2.setGeometry(QtCore.QRect(180, 370, 41, 41))
        self.h2.setObjectName("h2")
        self.h4 = QtWidgets.QPushButton(self.centralWidget)
        self.h4.setGeometry(QtCore.QRect(180, 290, 41, 41))
        self.h4.setObjectName("h4")
        self.h3 = QtWidgets.QPushButton(self.centralWidget)
        self.h3.setGeometry(QtCore.QRect(180, 330, 41, 41))
        self.h3.setObjectName("h3")
        self.h8 = QtWidgets.QPushButton(self.centralWidget)
        self.h8.setGeometry(QtCore.QRect(180, 130, 41, 41))
        self.h8.setObjectName("h8")
        self.h1 = QtWidgets.QPushButton(self.centralWidget)
        self.h1.setGeometry(QtCore.QRect(180, 410, 41, 41))
        self.h1.setObjectName("h1")
        self.h7 = QtWidgets.QPushButton(self.centralWidget)
        self.h7.setGeometry(QtCore.QRect(180, 170, 41, 41))
        self.h7.setObjectName("h7")
        self.b13 = QtWidgets.QPushButton(self.centralWidget)
        self.b13.setGeometry(QtCore.QRect(220, 330, 41, 41))
        self.b13.setObjectName("b13")
        self.b12 = QtWidgets.QPushButton(self.centralWidget)
        self.b12.setGeometry(QtCore.QRect(220, 370, 41, 41))
        self.b12.setObjectName("b12")
        self.b18 = QtWidgets.QPushButton(self.centralWidget)
        self.b18.setGeometry(QtCore.QRect(220, 130, 41, 41))
        self.b18.setObjectName("b18")
        self.b15 = QtWidgets.QPushButton(self.centralWidget)
        self.b15.setGeometry(QtCore.QRect(220, 250, 41, 41))
        self.b15.setObjectName("b15")
        self.b14 = QtWidgets.QPushButton(self.centralWidget)
        self.b14.setGeometry(QtCore.QRect(220, 290, 41, 41))
        self.b14.setObjectName("b14")
        self.b17 = QtWidgets.QPushButton(self.centralWidget)
        self.b17.setGeometry(QtCore.QRect(220, 170, 41, 41))
        self.b17.setObjectName("b17")
        self.b16 = QtWidgets.QPushButton(self.centralWidget)
        self.b16.setGeometry(QtCore.QRect(220, 210, 41, 41))
        self.b16.setObjectName("b16")
        self.b11 = QtWidgets.QPushButton(self.centralWidget)
        self.b11.setGeometry(QtCore.QRect(220, 410, 41, 41))
        self.b11.setObjectName("b11")
        self.b23 = QtWidgets.QPushButton(self.centralWidget)
        self.b23.setGeometry(QtCore.QRect(260, 330, 41, 41))
        self.b23.setObjectName("b23")
        self.b22 = QtWidgets.QPushButton(self.centralWidget)
        self.b22.setGeometry(QtCore.QRect(260, 370, 41, 41))
        self.b22.setObjectName("b22")
        self.b28 = QtWidgets.QPushButton(self.centralWidget)
        self.b28.setGeometry(QtCore.QRect(260, 130, 41, 41))
        self.b28.setObjectName("b28")
        self.b25 = QtWidgets.QPushButton(self.centralWidget)
        self.b25.setGeometry(QtCore.QRect(260, 250, 41, 41))
        self.b25.setObjectName("b25")
        self.b24 = QtWidgets.QPushButton(self.centralWidget)
        self.b24.setGeometry(QtCore.QRect(260, 290, 41, 41))
        self.b24.setObjectName("b24")
        self.b27 = QtWidgets.QPushButton(self.centralWidget)
        self.b27.setGeometry(QtCore.QRect(260, 170, 41, 41))
        self.b27.setObjectName("b27")
        self.b26 = QtWidgets.QPushButton(self.centralWidget)
        self.b26.setGeometry(QtCore.QRect(260, 210, 41, 41))
        self.b26.setObjectName("b26")
        self.b21 = QtWidgets.QPushButton(self.centralWidget)
        self.b21.setGeometry(QtCore.QRect(260, 410, 41, 41))
        self.b21.setObjectName("b21")
        self.b33 = QtWidgets.QPushButton(self.centralWidget)
        self.b33.setGeometry(QtCore.QRect(300, 330, 41, 41))
        self.b33.setObjectName("b33")
        self.b32 = QtWidgets.QPushButton(self.centralWidget)
        self.b32.setGeometry(QtCore.QRect(300, 370, 41, 41))
        self.b32.setObjectName("b32")
        self.b38 = QtWidgets.QPushButton(self.centralWidget)
        self.b38.setGeometry(QtCore.QRect(300, 130, 41, 41))
        self.b38.setObjectName("b38")
        self.b35 = QtWidgets.QPushButton(self.centralWidget)
        self.b35.setGeometry(QtCore.QRect(300, 250, 41, 41))
        self.b35.setObjectName("b35")
        self.b34 = QtWidgets.QPushButton(self.centralWidget)
        self.b34.setGeometry(QtCore.QRect(300, 290, 41, 41))
        self.b34.setObjectName("b34")
        self.b37 = QtWidgets.QPushButton(self.centralWidget)
        self.b37.setGeometry(QtCore.QRect(300, 170, 41, 41))
        self.b37.setObjectName("b37")
        self.b36 = QtWidgets.QPushButton(self.centralWidget)
        self.b36.setGeometry(QtCore.QRect(300, 210, 41, 41))
        self.b36.setObjectName("b36")
        self.b31 = QtWidgets.QPushButton(self.centralWidget)
        self.b31.setGeometry(QtCore.QRect(300, 410, 41, 41))
        self.b31.setObjectName("b31")
        self.b43 = QtWidgets.QPushButton(self.centralWidget)
        self.b43.setGeometry(QtCore.QRect(340, 330, 41, 41))
        self.b43.setObjectName("b43")
        self.b42 = QtWidgets.QPushButton(self.centralWidget)
        self.b42.setGeometry(QtCore.QRect(340, 370, 41, 41))
        self.b42.setObjectName("b42")
        self.b48 = QtWidgets.QPushButton(self.centralWidget)
        self.b48.setGeometry(QtCore.QRect(340, 130, 41, 41))
        self.b48.setObjectName("b48")
        self.b45 = QtWidgets.QPushButton(self.centralWidget)
        self.b45.setGeometry(QtCore.QRect(340, 250, 41, 41))
        self.b45.setObjectName("b45")
        self.b44 = QtWidgets.QPushButton(self.centralWidget)
        self.b44.setGeometry(QtCore.QRect(340, 290, 41, 41))
        self.b44.setObjectName("b44")
        self.b47 = QtWidgets.QPushButton(self.centralWidget)
        self.b47.setGeometry(QtCore.QRect(340, 170, 41, 41))
        self.b47.setObjectName("b47")
        self.b46 = QtWidgets.QPushButton(self.centralWidget)
        self.b46.setGeometry(QtCore.QRect(340, 210, 41, 41))
        self.b46.setObjectName("b46")
        self.b41 = QtWidgets.QPushButton(self.centralWidget)
        self.b41.setGeometry(QtCore.QRect(340, 410, 41, 41))
        self.b41.setObjectName("b41")
        self.b53 = QtWidgets.QPushButton(self.centralWidget)
        self.b53.setGeometry(QtCore.QRect(380, 330, 41, 41))
        self.b53.setObjectName("b53")
        self.b52 = QtWidgets.QPushButton(self.centralWidget)
        self.b52.setGeometry(QtCore.QRect(380, 370, 41, 41))
        self.b52.setObjectName("b52")
        self.b58 = QtWidgets.QPushButton(self.centralWidget)
        self.b58.setGeometry(QtCore.QRect(380, 130, 41, 41))
        self.b58.setObjectName("b58")
        self.b55 = QtWidgets.QPushButton(self.centralWidget)
        self.b55.setGeometry(QtCore.QRect(380, 250, 41, 41))
        self.b55.setObjectName("b55")
        self.b54 = QtWidgets.QPushButton(self.centralWidget)
        self.b54.setGeometry(QtCore.QRect(380, 290, 41, 41))
        self.b54.setObjectName("b54")
        self.b57 = QtWidgets.QPushButton(self.centralWidget)
        self.b57.setGeometry(QtCore.QRect(380, 170, 41, 41))
        self.b57.setObjectName("b57")
        self.b56 = QtWidgets.QPushButton(self.centralWidget)
        self.b56.setGeometry(QtCore.QRect(380, 210, 41, 41))
        self.b56.setObjectName("b56")
        self.b51 = QtWidgets.QPushButton(self.centralWidget)
        self.b51.setGeometry(QtCore.QRect(380, 410, 41, 41))
        self.b51.setObjectName("b51")
        self.b63 = QtWidgets.QPushButton(self.centralWidget)
        self.b63.setGeometry(QtCore.QRect(420, 330, 41, 41))
        self.b63.setObjectName("b63")
        self.b62 = QtWidgets.QPushButton(self.centralWidget)
        self.b62.setGeometry(QtCore.QRect(420, 370, 41, 41))
        self.b62.setObjectName("b62")
        self.b68 = QtWidgets.QPushButton(self.centralWidget)
        self.b68.setGeometry(QtCore.QRect(420, 130, 41, 41))
        self.b68.setObjectName("b68")
        self.b65 = QtWidgets.QPushButton(self.centralWidget)
        self.b65.setGeometry(QtCore.QRect(420, 250, 41, 41))
        self.b65.setObjectName("b65")
        self.b64 = QtWidgets.QPushButton(self.centralWidget)
        self.b64.setGeometry(QtCore.QRect(420, 290, 41, 41))
        self.b64.setObjectName("b64")
        self.b67 = QtWidgets.QPushButton(self.centralWidget)
        self.b67.setGeometry(QtCore.QRect(420, 170, 41, 41))
        self.b67.setObjectName("b67")
        self.b66 = QtWidgets.QPushButton(self.centralWidget)
        self.b66.setGeometry(QtCore.QRect(420, 210, 41, 41))
        self.b66.setObjectName("b66")
        self.b61 = QtWidgets.QPushButton(self.centralWidget)
        self.b61.setGeometry(QtCore.QRect(420, 410, 41, 41))
        self.b61.setObjectName("b61")
        self.b73 = QtWidgets.QPushButton(self.centralWidget)
        self.b73.setGeometry(QtCore.QRect(460, 330, 41, 41))
        self.b73.setObjectName("b73")
        self.b72 = QtWidgets.QPushButton(self.centralWidget)
        self.b72.setGeometry(QtCore.QRect(460, 370, 41, 41))
        self.b72.setObjectName("b72")
        self.b78 = QtWidgets.QPushButton(self.centralWidget)
        self.b78.setGeometry(QtCore.QRect(460, 130, 41, 41))
        self.b78.setObjectName("b78")
        self.b75 = QtWidgets.QPushButton(self.centralWidget)
        self.b75.setGeometry(QtCore.QRect(460, 250, 41, 41))
        self.b75.setObjectName("b75")
        self.b74 = QtWidgets.QPushButton(self.centralWidget)
        self.b74.setGeometry(QtCore.QRect(460, 290, 41, 41))
        self.b74.setObjectName("b74")
        self.b77 = QtWidgets.QPushButton(self.centralWidget)
        self.b77.setGeometry(QtCore.QRect(460, 170, 41, 41))
        self.b77.setObjectName("b77")
        self.b76 = QtWidgets.QPushButton(self.centralWidget)
        self.b76.setGeometry(QtCore.QRect(460, 210, 41, 41))
        self.b76.setObjectName("b76")
        self.b71 = QtWidgets.QPushButton(self.centralWidget)
        self.b71.setGeometry(QtCore.QRect(460, 410, 41, 41))
        self.b71.setObjectName("b71")
        self.b83 = QtWidgets.QPushButton(self.centralWidget)
        self.b83.setGeometry(QtCore.QRect(500, 330, 41, 41))
        self.b83.setObjectName("b83")
        self.b82 = QtWidgets.QPushButton(self.centralWidget)
        self.b82.setGeometry(QtCore.QRect(500, 370, 41, 41))
        self.b82.setObjectName("b82")
        self.b88 = QtWidgets.QPushButton(self.centralWidget)
        self.b88.setGeometry(QtCore.QRect(500, 130, 41, 41))
        self.b88.setObjectName("b88")
        self.b85 = QtWidgets.QPushButton(self.centralWidget)
        self.b85.setGeometry(QtCore.QRect(500, 250, 41, 41))
        self.b85.setObjectName("b85")
        self.b84 = QtWidgets.QPushButton(self.centralWidget)
        self.b84.setGeometry(QtCore.QRect(500, 290, 41, 41))
        self.b84.setObjectName("b84")
        self.b87 = QtWidgets.QPushButton(self.centralWidget)
        self.b87.setGeometry(QtCore.QRect(500, 170, 41, 41))
        self.b87.setObjectName("b87")
        self.b86 = QtWidgets.QPushButton(self.centralWidget)
        self.b86.setGeometry(QtCore.QRect(500, 210, 41, 41))
        self.b86.setObjectName("b86")
        self.b81 = QtWidgets.QPushButton(self.centralWidget)
        self.b81.setGeometry(QtCore.QRect(500, 410, 41, 41))
        self.b81.setObjectName("b81")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 890, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Temperature (C)"))
        self.txtFlow.setText(_translate("MainWindow", "Flow Rate"))
        self.label_2.setText(_translate("MainWindow", "Flow Rate"))
        self.label_3.setText(_translate("MainWindow", "Cold"))
        self.label_4.setText(_translate("MainWindow", "Hot"))
        self.manualButton.setText(_translate("MainWindow", "Faucet Handle Control"))
        self.pshBut2.setText(_translate("MainWindow", "Stop"))
        self.c0.setText(_translate("MainWindow", "0"))
        self.c1.setText(_translate("MainWindow", "1, 0"))
        self.c2.setText(_translate("MainWindow", "2, 0"))
        self.c3.setText(_translate("MainWindow", "3, 0"))
        self.c7.setText(_translate("MainWindow", "7, 0"))
        self.c6.setText(_translate("MainWindow", "6, 0"))
        self.c4.setText(_translate("MainWindow", "4, 0"))
        self.c5.setText(_translate("MainWindow", "5, 0"))
        self.c8.setText(_translate("MainWindow", "8, 0"))
        self.h0.setText(_translate("MainWindow", "0, 0"))
        self.h5.setText(_translate("MainWindow", "0, 5"))
        self.h6.setText(_translate("MainWindow", "0, 6"))
        self.h2.setText(_translate("MainWindow", "0, 2"))
        self.h4.setText(_translate("MainWindow", "0, 4"))
        self.h3.setText(_translate("MainWindow", "0, 3"))
        self.h8.setText(_translate("MainWindow", "0, 8"))
        self.h1.setText(_translate("MainWindow", "0, 1"))
        self.h7.setText(_translate("MainWindow", "0, 7"))
        self.b13.setText(_translate("MainWindow", "1, 3"))
        self.b12.setText(_translate("MainWindow", "1, 2"))
        self.b18.setText(_translate("MainWindow", "1, 8"))
        self.b15.setText(_translate("MainWindow", "1, 5"))
        self.b14.setText(_translate("MainWindow", "1, 4"))
        self.b17.setText(_translate("MainWindow", "1, 7"))
        self.b16.setText(_translate("MainWindow", "1, 6"))
        self.b11.setText(_translate("MainWindow", "1, 1"))
        self.b23.setText(_translate("MainWindow", "2, 3"))
        self.b22.setText(_translate("MainWindow", "2, 2"))
        self.b28.setText(_translate("MainWindow", "2, 8"))
        self.b25.setText(_translate("MainWindow", "2, 5"))
        self.b24.setText(_translate("MainWindow", "2, 4"))
        self.b27.setText(_translate("MainWindow", "2, 7"))
        self.b26.setText(_translate("MainWindow", "2, 6"))
        self.b21.setText(_translate("MainWindow", "2, 1"))
        self.b33.setText(_translate("MainWindow", "3, 3"))
        self.b32.setText(_translate("MainWindow", "3, 2"))
        self.b38.setText(_translate("MainWindow", "3, 8"))
        self.b35.setText(_translate("MainWindow", "3, 5"))
        self.b34.setText(_translate("MainWindow", "3, 4"))
        self.b37.setText(_translate("MainWindow", "3, 7"))
        self.b36.setText(_translate("MainWindow", "3, 6"))
        self.b31.setText(_translate("MainWindow", "3, 1"))
        self.b43.setText(_translate("MainWindow", "4, 3"))
        self.b42.setText(_translate("MainWindow", "4, 2"))
        self.b48.setText(_translate("MainWindow", "4, 8"))
        self.b45.setText(_translate("MainWindow", "4, 5"))
        self.b44.setText(_translate("MainWindow", "4, 4"))
        self.b47.setText(_translate("MainWindow", "4, 7"))
        self.b46.setText(_translate("MainWindow", "4, 6"))
        self.b41.setText(_translate("MainWindow", "4, 1"))
        self.b53.setText(_translate("MainWindow", "5, 3"))
        self.b52.setText(_translate("MainWindow", "5, 2"))
        self.b58.setText(_translate("MainWindow", "5, 8"))
        self.b55.setText(_translate("MainWindow", "5, 5"))
        self.b54.setText(_translate("MainWindow", "5, 4"))
        self.b57.setText(_translate("MainWindow", "5, 7"))
        self.b56.setText(_translate("MainWindow", "5, 6"))
        self.b51.setText(_translate("MainWindow", "5, 1"))
        self.b63.setText(_translate("MainWindow", "6, 3"))
        self.b62.setText(_translate("MainWindow", "6, 2"))
        self.b68.setText(_translate("MainWindow", "6, 8"))
        self.b65.setText(_translate("MainWindow", "6, 5"))
        self.b64.setText(_translate("MainWindow", "6, 4"))
        self.b67.setText(_translate("MainWindow", "6, 7"))
        self.b66.setText(_translate("MainWindow", "6, 6"))
        self.b61.setText(_translate("MainWindow", "6, 1"))
        self.b73.setText(_translate("MainWindow", "7, 3"))
        self.b72.setText(_translate("MainWindow", "7, 2"))
        self.b78.setText(_translate("MainWindow", "7, 8"))
        self.b75.setText(_translate("MainWindow", "7, 5"))
        self.b74.setText(_translate("MainWindow", "7, 4 "))
        self.b77.setText(_translate("MainWindow", "7, 7"))
        self.b76.setText(_translate("MainWindow", "7, 6"))
        self.b71.setText(_translate("MainWindow", "7, 1"))
        self.b83.setText(_translate("MainWindow", "8, 3"))
        self.b82.setText(_translate("MainWindow", "8, 2"))
        self.b88.setText(_translate("MainWindow", "8, 8"))
        self.b85.setText(_translate("MainWindow", "8, 5"))
        self.b84.setText(_translate("MainWindow", "8, 4"))
        self.b87.setText(_translate("MainWindow", "8, 7"))
        self.b86.setText(_translate("MainWindow", "8, 6"))
        self.b81.setText(_translate("MainWindow", "8, 1"))

